### ISSUE TITLE
annotations are missing!

### ISSUE THREAD

**Issue by ENJOY-Yin-jiong** [shuoyang129/eamat#1]
Nice work and thank you for your kindly sharing! 
However, you maybe forget to share your own annotations on three datasets while sharing. I am looking forward to reproducing your work sincerely!
Thank you!

**Comment by shuoyang129** [comment]
Thanks for your attention. I use public annotations like VSLNet, which has a detailed data processing procedure. You can find them at  https://github.com/IsaacChanghau/VSLNet/tree/master/prepare.

**Comment by ENJOY-Yin-jiong** [comment]
Thank you for your code and help.
