### ISSUE TITLE
How to calculate R@5, Iou=0.1/0.3/0.7...etc?

### ISSUE THREAD

**Issue by ShaneeyS** [shuoyang129/eamat#3]
Hi, i notice that the provided script contains the code for calculating Rank=1, IoU=0.3/0.5/0.7, but i do not find the code to calculate Rank=5, IoU=xxx. Could you please release the code for calculating metrics w.r.t. Rank=5?

**Comment by shuoyang129** [comment]
For rank 5, you can see this link:  https://github.com/microsoft/VideoX/blob/master/2D-TAN/lib/core/eval.py.
Most proposal-based methods calculate the rank5-related metric.

**Comment by ShaneeyS** [comment]
So, for proposal-free methods, like VSLNet and eamat, calculate rank5-related metric is not fair, right? Because proposal-free methods may not good at predicting rank5 results than those proposal-based methods? Am I right?

**Comment by shuoyang129** [comment]
Most propose-free methods regress the bounding box with only one result, which is unable to calculate rank-5 related metrics.

**Comment by ShaneeyS** [comment]
So would it possible to calculate rank-5 related metrics for VSLNet and eamat? Thanks a lot.
